name: CI
on: [push]
jobs:
  analyze:
    name: Run PMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: pmd
        uses: rtjl/pmd-analyzer-action@v0.1.5-alpha
        with:
          pmd-version: '6.31.0'
          source-path: './src'
          rule-path: './PMD.Rules.xml'
